version: '2.3'
services:
  app:
    build:
      context: ${PWD}
      dockerfile: Dockerfile
    environment:
      - DISPLAY_ERRORS=On
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 8000:80
    networks:
      - application
      - codelytv-network
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ${PWD}/migrations:/docker-entrypoint-initdb.d
    networks:
      - admin
      - codelytv-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - admin
    depends_on:
      - mysql

networks:
  codelytv-network:
    external:
      name: codelytv-network
  admin:
  application:
  other_network:
